on: workflow_dispatch

jobs:
  create-tarball:
    runs-on: macos-latest

    steps:
      - run: |
          brew install dbus glib

          export DBUSFOLDER=/usr/local/Cellar/dbus/`ls /usr/local/Cellar/dbus`/bin/
          export GLIBFOLDER=/usr/local/Cellar/glib/`ls /usr/local/Cellar/glib`/bin/
          export CWD=`pwd`
          cd $DBUSFOLDER && tar -cvf $CWD/gdbus.tar * && cd $CWD
          cd $GLIBFOLDER && tar -rvf $CWD/gdbus.tar gdbus* && cd $CWD
          gzip < gdbus.tar > gdbus.tgz

      - uses: actions/upload-artifact@v2
        with:
          path: |
            gdbus.tgz
