on: workflow_dispatch

jobs:
  create-tarball:
    runs-on: macos-latest

    steps:
      - run: |
          brew install dbus

          export FOLDER=/usr/local/Cellar/dbus/`ls /usr/local/Cellar/dbus`/bin/
          export CWD=`pwd`
          cd $FOLDER && tar -zcvf $CWD/gdbus.tgz * && cd -

      - uses: actions/upload-artifact@v2
        with:
          path: |
            gdbus.tgz
